### ISSUE TITLE
Create Variant of Concern Map Visualization

### ISSUE THREAD

**Issue by calremmel** [globaldothealth/list#1501]
We would like to create a way to explore the data that includes information on Variants of Concern visually. The following elements are proposed:

- [ ] The visualization should be available as a top-level nav item, along with Country, Regional, and Completeness views.
- [ ] The visualization should be a choropleth map that displays counts of data with variant info by country.
- [ ] There should be a way to filter for particular variants. This should not replace the sidebar.
- [ ] Sidebar should still show country counts, as this is useful for navigation, filtering, and comparing variant counts.
- [ ] Users should be able to filter data by country and variant using the map.
- [ ] There should be a display of counts of Public and Private data on the tooltip, so users will know what data they can view and download. This can perhaps be something like Coverage view.
- [ ] There should be an explanation of what data is public/private and why, either on tooltips or as part of a guide/FAQ.

Prerequisites:

- [x] Implementation of VoC field #1483
- [x] Implementation of filtering by VoC field #1502
- [ ] Generation of JSON with variant counts by country #1504

Nice-to-have:

- [ ] Small table or horizontal bars showing variant counts on country tooltip

**Comment by joe-brilliant** [comment]
Thanks @calremmel !! Here are a couple of links from @Mougk's team that might be instructive:

https://en.wikipedia.org/wiki/Variant_of_Concern_202012/01
https://www.cdc.gov/coronavirus/2019-ncov/transmission/variant-cases.html
https://cov-lineages.org/global_report.html

**Comment by joe-brilliant** [comment]
@scarpino your input here would be much appreciated !

**Comment by calremmel** [comment]
Added a couple of requirements from discussion on public vs. private data sources.

**Comment by scarpino** [comment]
> @scarpino your input here would be much appreciated !

I think that as described this is a great launch MVP. Keeping things simple and just advertising that we have these data achieves our objective.
