### ISSUE TITLE
Beta Bug Bash + Homestretch Housekeeping

### ISSUE THREAD

**Issue by joe-brilliant** [globaldothealth/list#1508]
- [x] Fix visualization issues with Regional view on Map
- [x] Update URLs for Country View and Regional view to be more accurate and descriptive (currently: http://covid-19.global.health/#cumulative and http://covid-19.global.health/#cases)
- [x] Fix issue generating error message when signing up with non Google email after entering security code
- [x] Add the top nav link on Map that links to Data (similar to the corresponding link on Data top nav that links to Map)
- [x] Make upper left "G.h" icon on Data go to homepage (marketing website)
- [x] Make upper left "G.h" icon on Map go to homepage (marketing website)
- [x] Update links on Data left nav sidebar (when opened) and profile modal (currently they link to old TOU, PP, etc
https://www.dropbox.com/s/biy4b7iydnodr6y/Screen%20Shot%202021-02-03%20at%204.24.33%20PM.png?dl=0
https://www.dropbox.com/s/i3uv2j3485w0xrs/Screen%20Shot%202021-02-03%20at%204.24.05%20PM.png?dl=0
- [x] Change "About Global.Health" in profile modal on Data to "Global.health" and fix link to go to "About page" 
- [x] Remove "Report an issue" from profile modal on Data
- [x] Add link to "Privacy Policy" under "Get Involved" webform on marketing website
- [x] Update header metadata preview links for homepage, Data, and Map and test preview tiles on social media (text should say "Global.health | a Data Science Initiative" on web, and "G.h | a Data Science Initiative" on mobile if there are dynamic options)
- [x] Optimize site loading speed for marketing website (especially "About")
- [x] Ensure all text font colors are consistent on About (specifically Emily Cohn's title)
- [x] Add links to TOU and PP in login/sign up interstitial page
- [x] Update all partner logos on homepage, about, and sign up interstitial
https://drive.google.com/drive/folders/1VuWAO4oxSex8J9oKtstXCUCJH7GOHjJr
- [x] Fix top justification of signup interstitial (cuts off at the top) https://www.dropbox.com/s/r7iyi9f8m270se2/Screen%20Shot%202021-02-04%20at%2010.48.04%20AM.png?dl=0
- [x] Customize language in non Google email confirmation email (this might need to be a separate issue)
- [x] Add updated email, contact info, and all needed links in TOU and PP
- [x] Fix text field alignment on email signup form (crops a bit at the bottom?)
- [x] Remove H1N1 from left nav dropdown on Map  https://www.dropbox.com/s/rcliio3cdoix1wy/Screen%20Shot%202021-02-04%20at%2012.45.28%20PM.png?dl=0
- [x] Confirm iubenda GDPR and cookie policy pop up is implemented and behaving correctly
- [x] Change homepage footer copyright text from "Copyright 2021, Boston Children's Hospital" to just "Copyright 2021"
- [x] #1528 Filtering by country doesn't always work
- [x] #1529 Unstructured queries on Data do not always show relevant results 
- [x] #1545 "null" values in "regional data" causing misleading/confusing data visualizations on Map
- [x] #1548 Re-ingest missing cases and identify reason for their unintended removal from database
- [x] Missing button text on cookie policy popup https://drive.google.com/file/d/1mG3eLiiMwTO1ek4VG2SM3EcnNu3owJqC/view
- [x] Change "Global.Health" text to "About Global.health" in user profile dropdown in upper right corner of Data page
https://www.dropbox.com/s/zlbe7h8v4c7zdmf/Screen%20Shot%202021-02-12%20at%2010.06.32%20AM.png?dl=0
- [x] Add links to "Data acknowledgments" in the lower left of Data page (when pane is expanded), user profile drop down in the upper right of data page, and the links on the login page:
https://www.dropbox.com/s/war7y6br5cxexvq/Screen%20Shot%202021-02-12%20at%2010.05.23%20AM.png?dl=0
https://www.dropbox.com/s/zlbe7h8v4c7zdmf/Screen%20Shot%202021-02-12%20at%2010.06.32%20AM.png?dl=0
https://www.dropbox.com/s/c0lxdqig26fe361/Screen%20Shot%202021-02-12%20at%2010.06.02%20AM.png?dl=0

- [x] On Data page, fix link so that only the "G.h" icon on the upper left goes to the homepage, not the word "Data" (the word "Data" should link back to / reload the default Data page)

- [x] "Coming soon modal" appears when anywhere in the top nav or buttons in the middle of homepage (not just "Map" and "Data")
- [x] Get Involved link on Research goes to dev URL
- [x] Replace Harvard logo on login / landing page with HMS logo
- [x] Newsletter opt in checkbox text on login / landing page should read "I agree to be added to the Global.health newsletter"
- [x] Fix formatting for "G.h Map" text and download button on data when screen size is reduced
https://www.dropbox.com/s/3ury8xhefoy1eto/Screen%20Shot%202021-02-19%20at%203.51.18%20PM.png?dl=0
- [x] Fix welcome emails #1527 
- [x] Change "Global.Health" to "Global.health" (lowecase "h") in profile dropdown menu on Data
https://www.dropbox.com/s/aos61ftp4m6wf6o/Screen%20Shot%202021-02-20%20at%202.32.51%20PM.png?dl=0
- [x] Adjust size of Georgetown logo on homepage, About page, and data login/landing page accordingly: _"I know our stacked logo isn’t idea (because of the seal), but can you make it just a wee bit larger so the font of “Center for Global Health Science and Security” is equal in size to "Center for Health Security” at the bottom of Hopkins logo?  I think the gray font color will help it not look overly large once you do that.”_
- [x] Unhide FAQ in website footer
- [x] Add JHU to Data Acknowledgments 
https://coronavirus.jhu.edu/map.html
- [x] Embed YouTube Video on HP upon receipt #1381 
- [x] Test GA #1524 
- [x] Confirm we are tracking email addresses of users who DL the dataset #1593 
- [x] When viewing homepage on mobile “explore data” should go under the text, not the video
https://www.dropbox.com/s/tpsb729hxxjw4x0/Screen%20Shot%202021-02-21%20at%209.26.58%20AM.png?dl=0
- [x] When clicking through from some countries on Map (eg. Algeria) the total case results on Data differ
- [x] Verify **all main Global.health domain** card previews function correctly on Twitter, LinkedIn, Slack, and iMesssage etc

(In particular, the Data link previews still say "Curator portal" etc on slack etc. The Map previews look good on Slack)

https://cards-dev.twitter.com/validator
https://www.linkedin.com/post-inspector/inspect/
https://api.slack.com/methods/chat.unfurl/test
https://developer.apple.com/library/archive/technotes/tn2444/_index.html

https://global.health/
https://global.health/research/
https://global.health/about/
https://data.covid-19.global.health/
https://data.covid-19.global.health/cases
https://map.covid-19.global.health/
https://map.covid-19.global.health/#country
https://map.covid-19.global.health/#region
https://map.covid-19.global.health/#coverage

- [x] Align top of video and text on website homepage https://dev-globalhealth.pantheonsite.io/
 https://www.dropbox.com/s/obzxg1nkeykbn0t/Screen%20Shot%202021-02-21%20at%209.26.22%20AM.png?dl=0

- [x] G.h logo link in upper left corner of Map goes to https://test-globalhealth.pantheonsite.io/, should go to http://global.health/
- [x] Change 3rd research entry on main page to: https://www.nature.com/articles/s41597-020-0448-0
- [x] Fix links to FAQ and Data Acks on Map Help Modal https://github.com/globaldothealth/list/issues/1526#issuecomment-783638265 re: #1526 
- [x] Add correct links to Data Acks on data page profile drop down and sidebar text
https://www.dropbox.com/s/v828gq0jbesgnwc/Screen%20Shot%202021-02-22%20at%203.17.04%20PM.png?dl=0
https://www.dropbox.com/s/54yfc71ejxox18b/Screen%20Shot%202021-02-22%20at%203.16.40%20PM.png?dl=0

- [x] Change font on Map help modal to be the same as the font on the Data help modal
 https://www.dropbox.com/s/vz2vwxkk9pmexbr/Screen%20Shot%202021-02-22%20at%209.14.11%20PM.png?dl=0
https://www.dropbox.com/s/e0bu3h4pqa9bo6v/Screen%20Shot%202021-02-22%20at%209.14.41%20PM.png?dl=0

- [x] Change "Global.Health" to "Global.health" on Terms of Use page header

**Comment by rkassa** [comment]
Update from my end:

> * [x]  Fix visualization issues with Regional view on Map
> * [x]  Update URLs for Country View and Regional view to be more accurate and descriptive (currently: http://covid-19.global.health/#cumulative and http://covid-19.global.health/#cases)
> * [x]  Add the top nav link on Map that links to Data (similar to the corresponding link on Data top nav that links to Map)
> * [x]  Make upper left "G.h" icon on Map go to homepage (marketing website)
> * [x]  Add link to "Privacy Policy" under "Get Involved" webform on marketing website
> * [x]  Optimize site loading speed for marketing website (especially "About")

**Comment by joe-brilliant** [comment]
I am still noticing somewhat slow loading times on the marketing website, particularly "About" @rkassa. Are you? Would you mind taking a look and maybe revisiting compression once we add new logos  ? Thank you!

**Comment by rkassa** [comment]
Additional fixes —

> * [x] Update header metadata preview links for homepage, Data, and Map and test preview tiles on social media (text should say "Global.health | a Data Science Initiative" on web, and "G.h | a Data Science Initiative" on mobile if there are dynamic options)
> * [x]  Remove H1N1 from left nav dropdown on Map  https://www.dropbox.com/s/rcliio3cdoix1wy/Screen%20Shot%202021-02-04%20at%2012.45.28%20PM.png?dl=0

**Comment by WeronikaMichaluk** [comment]
@rkassa could you please advise regarding 
Ensure all text font colors are consistent on About (specifically Emily Cohn's title)

We are not sure where is the ABOUT site

**Comment by WeronikaMichaluk** [comment]
Update from HTD, Tasks that are done:

Make upper left "G.h" icon on Data go to homepage (marketing website)
Update links on Data left nav sidebar (when opened) and profile modal (currently they link to old TOU, PP, etc
Change "About Global.Health" in profile modal on Data to "Global.health" and fix link to go to "About page"
Remove "Report an issue" from profile modal on Data
Add links to TOU and PP in login/sign up interstitial page
Update all partner logos on homepage, about, and sign up interstitial (Updated on Data website)
Fix top justification of signup interstitial (cuts off at the top)
Fix text field alignment on email signup form (crops a bit at the bottom?)
Confirm iubenda GDPR and cookie policy pop up is implemented and behaving correctly

GREAT JOB @maciekz1996 and @sergioloporto !!!

**Comment by rkassa** [comment]
Addition fixes:

> - [x]  Ensure all text font colors are consistent on About (specifically Emily Cohn's title)
> - [x]  Change homepage footer copyright text from "Copyright 2021, Boston Children's Hospital" to just "Copyright 2021"

**Comment by joe-brilliant** [comment]
@WeronikaMichaluk @rkassa @calremmel @maciekz1996 @sergioloporto added a few new items here. If you see any new issues is beta feedback please feel free to add. Also still getting slow loading time on marketing website, maybe let's update on global.health proper and test?

**Comment by maciekz1996** [comment]
@joe-brilliant 

Todays update from HTD:
> * [x] Missing button text on cookie policy popup https://drive.google.com/file/d/1mG3eLiiMwTO1ek4VG2SM3EcnNu3owJqC/view
> * [x] Change "Global.Health" text to "About Global.health" in user profile dropdown in upper right corner of Data page
https://www.dropbox.com/s/zlbe7h8v4c7zdmf/Screen%20Shot%202021-02-12%20at%2010.06.32%20AM.png?dl=0
> * [x] Add links to "Data acknowledgments" in the lower left of Data page (when pane is expanded), user profile drop down in the upper right of data page, and the links on the login page:
https://www.dropbox.com/s/war7y6br5cxexvq/Screen%20Shot%202021-02-12%20at%2010.05.23%20AM.png?dl=0
https://www.dropbox.com/s/zlbe7h8v4c7zdmf/Screen%20Shot%202021-02-12%20at%2010.06.32%20AM.png?dl=0
https://www.dropbox.com/s/c0lxdqig26fe361/Screen%20Shot%202021-02-12%20at%2010.06.02%20AM.png?dl=0
> * [x] On Data page, fix link so that only the "G.h" icon on the upper left goes to the homepage, not the word "Data" (the word "Data" should link back to / reload the default Data page)

**Comment by joe-brilliant** [comment]
Thanks @maciekz1996 !!

**Comment by maciekz1996** [comment]
@joe-brilliant 

Update from HTD:

> - [x] Replace Harvard logo on login / landing page with HMS logo
> - [x] Newsletter opt in checkbox text on login / landing page should read "I agree to be added to the Global.health newsletter"

**Comment by joe-brilliant** [comment]
@WeronikaMichaluk @sergioloporto @maciekz1996, we added a few more small bugs to the BBB list above. When you sign on can you please take a look and get started with any that you can? One that we may need your help with is " Confirm we are tracking email addresses of users who DL the dataset", @calremmel is writing up a ticket now. Thanks everyone, home-stretch!

**Comment by joe-brilliant** [comment]
@WeronikaMichaluk @sergioloporto @maciekz1996 we could also use your help with confirming and testing all social share preview / metadata, added details to the tickbox above, copied here (cc: @rkassa) 

 Verify all main Global.health domain card previews function correctly on Twitter, LinkedIn, Slack, and iMesssage etc

https://cards-dev.twitter.com/validator
https://www.linkedin.com/post-inspector/inspect/
https://api.slack.com/methods/chat.unfurl/test
https://developer.apple.com/library/archive/technotes/tn2444/_index.html

https://global.health/
https://data.covid-19.global.health/
https://data.covid-19.global.health/cases
https://map.covid-19.global.health/
https://map.covid-19.global.health/#country
https://map.covid-19.global.health/#region
https://map.covid-19.global.health/#coverage

**Comment by rkassa** [comment]
Update:

> 
> - [x]  Unhide FAQ in website footer
> - [x] Add JHU to Data Acknowledgments https://coronavirus.jhu.edu/map.html (list is updated from google sheet)
> - [x] Embed YouTube Video on HP upon receipt #1381 (placeholder is in place on dev)
> - [x] Test GA #1524 (confirmed on g.h marketing website. feel free to login to analytics.google.com and look at data @joe-brilliant)
> - [x] When viewing homepage on mobile “explore data” should go under the text, not the video
> - [x] Verify all main Global.health domain card previews function correctly on Twitter, LinkedIn, Slack, and iMesssage etc


global.health —
<img width="1013" alt="Screen Shot 2021-02-21 at 1 43 41 PM" src="https://user-images.githubusercontent.com/201428/108636885-fec07500-7455-11eb-82b3-0506b055f599.png">

map.covid-19.global.health —
![Screen Shot 2021-02-21 at 3 42 07 PM](https://user-images.githubusercontent.com/201428/108638061-5f05e580-745b-11eb-9a0c-d7ec6a2b795e.png)

data.covid-19.global.health — 
@calremmel PR is open for social cards meta tag fix for Data: https://github.com/globaldothealth/list/pull/1587

**Comment by joe-brilliant** [comment]
Thanks @rkassa ! Can we test and verify previews for these links as well?

https://global.health/research/
https://global.health/about/

**Comment by joe-brilliant** [comment]
added a sub task for the logo link issue on Map above in the master list @rkassa ^

**Comment by rkassa** [comment]
> https://global.health/research/

confirming that both are good to go ✔️

**Comment by rkassa** [comment]
> * [x]  Align top of video and text on website homepage https://dev-globalhealth.pantheonsite.io/
>   https://www.dropbox.com/s/obzxg1nkeykbn0t/Screen%20Shot%202021-02-21%20at%209.26.22%20AM.png?dl=0
> * [x]  G.h logo link in upper left corner of Map goes to https://test-globalhealth.pantheonsite.io/, should go to http://global.health/

Also fixed — on dev, test *and* prod

**Comment by joe-brilliant** [comment]
@rkassa just to confirm, if we can tweak the vid + text alignment on HP so the tops _appear_ to be aligned (even if they are technically are : ) that would be great even as a bandaid fix so it doesn't distract. Thank you!

**Comment by joe-brilliant** [comment]
@sergioloporto @rkassa @maciekz1996 one small cosmetic change to Map: can we change the font on the Map help modal to be the same as the font on the Data help modal? Added to list above. Thanks! 

https://www.dropbox.com/s/vz2vwxkk9pmexbr/Screen%20Shot%202021-02-22%20at%209.14.11%20PM.png?dl=0
https://www.dropbox.com/s/e0bu3h4pqa9bo6v/Screen%20Shot%202021-02-22%20at%209.14.41%20PM.png?dl=0

**Comment by joe-brilliant** [comment]
@rkassa one small change I wasn't able to fix on Pantheon: Change "Global.Health" to "Global.health" on Terms of Use page header

**Comment by joe-brilliant** [comment]
@rkassa I think we can put BBB to bed after merge and deploy these last two finishing touches? LMK when we're G2G!

 Change font on Map help modal to be the same as the font on the Data help modal
https://www.dropbox.com/s/vz2vwxkk9pmexbr/Screen%20Shot%202021-02-22%20at%209.14.11%20PM.png?dl=0
https://www.dropbox.com/s/e0bu3h4pqa9bo6v/Screen%20Shot%202021-02-22%20at%209.14.41%20PM.png?dl=0

 Change "Global.Health" to "Global.health" on Terms of Use page header

**Comment by joe-brilliant** [comment]
@rkassa is the map help text font bug as good as bashed? Last one!

**Comment by rkassa** [comment]
This is ready here https://github.com/globaldothealth/viz/pull/100 

> - [ ]  Change font on Map help modal to be the same as the font on the Data help modal
> https://www.dropbox.com/s/vz2vwxkk9pmexbr/Screen%20Shot%202021-02-22%20at%209.14.11%20PM.png?dl=0
> https://www.dropbox.com/s/e0bu3h4pqa9bo6v/Screen%20Shot%202021-02-22%20at%209.14.41%20PM.png?dl=0
