### ISSUE TITLE
For launch/production URLS: Test and confirm implementation of Google Analytics on all site areas, database metrics (new registration emails and which users have DL'd dataset), Webform submissions (Get Involved + Newsletter), and iubenda cookie and GDPR tracking pop up. 

### ISSUE THREAD

**Issue by joe-brilliant** [globaldothealth/list#1524]
- [ ] Test and confirm the implementation of Google Analytics on all site areas (Website, Map, Data)
- [ ] Database metrics (new registration emails and which users have DL'd dataset), 
- [ ] Webform submissions (Get Involved + Newsletter)
- [ ] Iubenda cookie and GDPR tracking pop up.

**Comment by joe-brilliant** [comment]
Hi @calremmel @rkassa I see GA activity for the marketing website but not Map or Data URLS yet. Can we please double check everything is in place to track activity across all subdomains? Thank you! https://analytics.google.com/analytics/web/#/p259628960/reports/explorer?r=all-pages-and-screens
