### ISSUE TITLE
Tracking implementation of new VoC workflow

### ISSUE THREAD

**Issue by abhidg** [globaldothealth/list#1616]
Automated tracking of sources but manual upload is the current workflow, documented at #1532 

- [ ] Download content to database, see #1613 for source types
- [ ] Surface results to query - Google sheets?
- [ ] Content is annotated with obtained structure, keyword matches, NLP named entity recognition etc.
- [ ] Once verified, content is transformed daily to the Gh schema and uploaded to the database (either through mongoimport, or preferably ADI)

**Comment by abhidg** [comment]
See #1619 for automated extraction of VoC data issue.
