### ISSUE TITLE
Monitoring Checklist

### ISSUE THREAD

**Issue by ksewalk** [globaldothealth/list#2937]
We would like to create an ongoing procedure and documentation of system monitoring.

Task List:

- [ ] Monitoring of Website Data Downloads
- [ ] Monitoring of Website Traffic
- [ ] tbd
- [ ] tbd

The result of this ticket would be a Wiki page to document system monitoring (the hows and where)

**Comment by jim-sheldon** [comment]
But wait, there's more (and possible solutions):
- [ ] Service crashes (Slack)
- [ ] Job failures (Slack)
- [ ] Ops metrics (Cloudwatch metrics)
- [ ] Status dashboard (website?)

**Comment by jim-sheldon** [comment]
Need more info on ops metrics and status dashboard
